name: iOS CI/CD

on:
  push:
    branches:
      - yatin_cicd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
    
      - name: Install dependencies
        run: pod install
        
      - name: Set Environment Variables
        run: |
            echo "IDEFileSystemSynchronizedGroupsAreEnabled=NO" >> $GITHUB_ENV

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Run UI Tests
        run: |
           xcodebuild test \
            -workspace MommyMap.xcworkspace \
           -scheme MommyMapUITests \
            -sdk iphonesimulator \
            -destination ‘platform=iOS Simulator,name=iPhone 11,OS=17.4’ \
            CODE_SIGNING_ALLOWED=NO | xcpretty
            
            
      - name: Build App
        run: xcodebuild clean build -workspace MommyMap.xcworkspace -scheme MommyMap -configuration Release -destination "generic/platform=iOS"

      - name: Archive App
        env:
          IDEFileSystemSynchronizedGroupsAreEnabled: YES
        run: |
          xcodebuild archive \
          -workspace MommyMap.xcworkspace \
          -scheme MommyMap \
          -sdk iphoneos \
          -archivePath ${{ github.workspace }}/MommyMap.xcarchive \
          CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Export IPA
        run: |
          env IDEFileSystemSynchronizedGroupsAreEnabled=NO xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/MommyMap.xcarchive \
            -exportPath $RUNNER_TEMP/export \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO | xcpretty
