name: iOS CI/CD

on:
  push:
    branches:
      - yatin_cicd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
    
      - name: Install dependencies
        run: pod install
        
      - name: Set Environment Variables
        run: |
            echo "IDEFileSystemSynchronizedGroupsAreEnabled=NO" >> $GITHUB_ENV
            
     - name: Decode and Install Certificates
       run: |
        echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
        echo "${{ secrets.IOS_PROFILE }}" | base64 --decode > profile.mobileprovision

        # Install p12 certificate
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "${{ secrets.IOS_CERT_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

        # Move provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Run UI Tests
        run: |
           xcodebuild test \
            -workspace MommyMap.xcworkspace \
           -scheme MommyMap \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15 pro,OS=17.4" \
            CODE_SIGNING_ALLOWED=NO | xcpretty
            
      - name: Build
        run: |
            IDEFileSystemSynchronizedGroupsAreEnabled=YES xcodebuild clean build
            -workspace MommyMap.xcworkspace \
            -scheme MommyMap \
            -configuration Release \
            -destination “generic/platform=iOS” \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive App
        env:
            IDEFileSystemSynchronizedGroupsAreEnabled: NO
        run: |
          xcodebuild archive \
          -workspace MommyMap.xcworkspace \
          -scheme MommyMap \
          -sdk iphoneos \
          -archivePath ${{ github.workspace }}/MommyMap.xcarchive \
          -allowProvisioningUpdates \
          CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Export IPA
        run: |
          env IDEFileSystemSynchronizedGroupsAreEnabled=NO xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/MommyMap.xcarchive \
            -exportPath $RUNNER_TEMP/export \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO | xcpretty
