name: iOS CI/CD

on:
  push:
    branches:
      - yatin_cicd

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
        
      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
    
      - name: Install CocoaPods dependencies
        run: |
            cd ${{ github.workspace }}
            pod install --verbose
            
      - name: Check Installed Pods
        run: cat Podfile.lock | grep UBottomSheet
        
      - name: Check Pods Folder
        run: ls -R Pods | grep UBottomSheet || echo "UBottomSheet not found!"

#      - name: Set Environment Variables
#        run: |
#            echo "IDEFileSystemSynchronizedGroupsAreEnabled=NO" >> $GITHUB_ENV
            
      - name: Decode and Install Certificates
        run: |
          echo "${{ secrets.IOS_CERTIFICATE }}" | base64 --decode > certificate.p12
          echo "${{ secrets.IOS_PROFILE }}" | base64 --decode > profile.mobileprovision

          # Install p12 certificate
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.IOS_CERT_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          # Move provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
          
      - name: Run Specific UI Test
        run: |
            xcodebuild test \
            -workspace MommyMap.xcworkspace \
            -scheme MommyMapUITests \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4" \
            -testPlan MommyMapUITests \
            -only-testing:MommyMapUITests/MommyMapUITests/testExample \
            -enableCodeCoverage YES

#      - name: Run UI Tests
#        run: |
#           xcodebuild test \
#            -workspace MommyMap.xcworkspace \
#           -scheme MommyMapUITests \
#            -sdk iphonesimulator \
#            -destination "platform=iOS Simulator,name=iPhone 15 pro,OS=17.4" \
#            CODE_SIGNING_ALLOWED=NO | xcpretty
#            -enableCodeCoverage YES
            
#      - name: Set Framework Search Paths
#        run: |
#          xcodebuild clean build \
#            -workspace MommyMap.xcworkspace \
#            -scheme MommyMap \
#            -sdk iphoneos \
#            FRAMEWORK_SEARCH_PATHS="$(pwd)/Pods/**"
            
#      - name: Tests and Build App
#        run: |
#          xcodebuild clean build \
#            -workspace MommyMap.xcworkspace \
#            -scheme MommyMap \
#            -sdk iphoneos \
#            -destination "generic/platform=iOS" \
#            -UseModernBuildSystem=YES

#      - name: Archive App
#        env:
#            IDEFileSystemSynchronizedGroupsAreEnabled: NO
#        run: |
#          xcodebuild archive \
#          -workspace MommyMap.xcworkspace \
#          -scheme MommyMap \
#          -sdk iphoneos \
#          -archivePath ${{ github.workspace }}/MommyMap.xcarchive \
#          -allowProvisioningUpdates \
#          CODE_SIGNING_ALLOWED=NO | xcpretty

#      - name: Export IPA
#        run: |
#          xcodebuild -exportArchive \
#            -archivePath $RUNNER_TEMP/MommyMap.xcarchive \
#            -exportPath $RUNNER_TEMP/export \
#            -exportOptionsPlist ExportOptions.plist \
#            CODE_SIGNING_ALLOWED=NO | xcpretty
